val set_basename : string -> unit ;;
(** Sets the basename for the multiple SMT-LIB v2 scripts generated by the
 ** [apply] function. The name defaults to the basename of the original SMT-LIB
 ** script (i.e. the name with the file extension chopped).
 *)

val apply: Ast.script -> unit ;;
(** Generates an independent SMT-LIB script for each (check-sat) command.
 ** All the generated scripts will be placed inside files sharing the same
 ** prefix and numbered.
 ** This function also triggers the interpretation of (push n) and (pop n)
 ** commands. Thus, all generated files are devoid of such commands and should
 ** be correct w.r.t. to the initial intendend semantics.
 *)
